# Generated by Django 4.2.2 on 2023-07-30 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topping',
            name='category',
        ),
        migrations.AddField(
            model_name='topping',
            name='category',
            field=models.ManyToManyField(blank=True, default='None', to='order.category', verbose_name='Type of Dish'),
        ),
    ]
