# Generated by Django 4.2.2 on 2023-07-30 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_topping_category_topping_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='img',
        ),
        migrations.AddField(
            model_name='order',
            name='image',
            field=models.URLField(default='https://i.redd.it/xgw4znhmt4t51.jpg', max_length=255, verbose_name='Image URL'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.URLField(default='https://i.redd.it/xgw4znhmt4t51.jpg', max_length=255, verbose_name='Image URL'),
        ),
    ]
