# Generated by Django 4.2.2 on 2023-07-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_dish_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='topping',
        ),
        migrations.AddField(
            model_name='order',
            name='topping',
            field=models.CharField(default='None', max_length=255, verbose_name='Included Topping'),
        ),
    ]
