# Generated by Django 4.2.2 on 2023-07-24 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sizes',
            name='image',
        ),
    ]
