# Generated by Django 4.2.2 on 2023-07-24 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_sizes_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sizes',
            name='price',
        ),
    ]
