# Generated by Django 4.2.2 on 2023-07-25 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_sizes_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dinner_Platter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.CharField(default='https://img.freepik.com/premium-vector/male-cook-cooking-meal-profile-avatar-icon_48369-15378.jpg', max_length=225)),
                ('price_small', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_large', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField(default='This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.', max_length=225)),
                ('rating', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RenameModel(
            old_name='Sizes',
            new_name='Size',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='order',
            name='type',
        ),
        migrations.RemoveField(
            model_name='subs_topping',
            name='image',
        ),
        migrations.AddField(
            model_name='cart',
            name='delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='item',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='pizza',
            name='toppings',
            field=models.ManyToManyField(to='order.pizza_topping'),
        ),
        migrations.AddField(
            model_name='sicilian_pizza',
            name='toppings',
            field=models.ManyToManyField(to='order.pizza_topping'),
        ),
        migrations.AddField(
            model_name='sub',
            name='toppings',
            field=models.ManyToManyField(to='order.subs_topping'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.DeleteModel(
            name='Dinner_Platters',
        ),
    ]
