# Generated by Django 4.2.2 on 2023-07-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_order_topping_order_topping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_at',
            field=models.DateField(auto_now_add=True, verbose_name='Time'),
        ),
    ]
